name: ordered_iterable
description: Ordered iterable is a library for ordering collections (orderBy, orderByDescending, thenBy, thenByDescending).
version: 1.0.3
homepage: https://github.com/mezoni/ordered_iterable
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
