name: ordered_iterable
description: Multi-level (by more than one key simultaneously), hierarchical, stable sorting of iterable collections (orderBy, orderByDescending, thenBy, thenByDescending).
version: 1.0.9
homepage: https://github.com/mezoni/ordered_iterable
topics:
  - sort
  - sorting
  - collection
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection: ^1.19.1
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
